### ISSUE TITLE
Project Files

### ISSUE THREAD

**Issue by ghost** [alec101/OSInteraction#3]
Initial discussion on #1

I think automated tools like cmake are overkill right now. But we could offer a makefile and a visual studio project, i can take care of the makefile if that's ok. I am willing to bet that most if not everyone o can run a Makefile, even in windows with Cygwin or MingW64.

Dependencies and the like are a responsibility of the user who wants to compile from source, but we can offer a wiki entry about that.

**Comment by alec101** [comment]
I've gone a little in-depth about ide's on the other isue. There is already a kind of system in place. I should upload somehow, maybe use one of these git forks or whatever (im new to git too).

Direct input/XInput libs, etc, I think Microsoft doesn't like to make them available from other sources. The  user _must_ download from the Microsoft site, or else, we might get sued and sent to Guantanamo or something.

**Comment by ghost** [comment]
Thanks for the detailed write-up here and in the other issue(#2) as well.

CMake is a very common piece of software that creates build files for all IDE'S/Compilers for all platforms, a basic cmake is pretty easy to define but i think its a lot of overkill for now, it can download dependencies from pre-set links or github/svn/mercurial repos and set it all up for all platforms. Maybe its my lack of experience with it, but the project files it creates are really only userfull for the end user of the lib, since is basicly just a compile project (At least in visual studio).

Makefiles can be used by every single IDE option you linked, even Visual Studio (This one is not recommended),  you just have to select "External Build System". I can vouch for this one, since i did this with at least Netbeans and cblocks.

There's is no secret to makefiles and i can maintain them. I'am sure you will be able to change/understand them as well after a couple of looks at some commits.

So basicly, just a single Makefile and a Visual Studio Solution would do the trick.

**Comment by alec101** [comment]
Uploaded visual studio project , netbeans project.

XCode and CodeBlocks proj files are not done ATM. They need updates.

**Comment by ghost** [comment]
Sounds good, i think the proj preffix you suggested in #2 is a good ideia.
I will commit a general Makefile later today.

Think we can close this?

**Comment by alec101** [comment]
ye
